# Generated by Django 3.1 on 2020-08-24 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200825_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text="User's account is active or not.", verbose_name='Active Status'),
        ),
    ]
