# Generated by Django 3.1 on 2020-08-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edupoint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpaper',
            name='max_time',
            field=models.IntegerField(default=0, help_text='Maximum time for test to submit in seconds.', verbose_name='Max Time'),
        ),
    ]
