# Generated by Django 3.1 on 2020-08-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edupoint', '0003_auto_20200827_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpaper',
            name='slug',
            field=models.SlugField(blank=True, help_text='A user friendly url for test.', unique=True, verbose_name='URL'),
        ),
    ]
