# Generated by Django 3.1 on 2020-08-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplechoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multichoicequestion',
            name='answer_order',
            field=models.CharField(blank=True, choices=[('content', 'Content'), ('random', 'Random'), ('none', 'None')], default=('random', 'Random'), help_text='The order in which multiple choice answer options are displayed to the user', max_length=30, null=True, verbose_name='Answer Order'),
        ),
    ]
