# Generated by Django 3.1 on 2020-08-31 19:18

from django.db import migrations, models
import multiplechoice.models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplechoice', '0002_auto_20200825_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='figure',
            field=models.ImageField(blank=True, help_text='Figure for answer if any.', null=True, upload_to=multiplechoice.models.answer_image_path, verbose_name='Answer Figure'),
        ),
    ]
